---
title: "Proyecto MELOCACTUS"
author: "D. S. Fernández del Viso"
format: docx
editor: visual
---

## Análisis de los datos del archivo `melocactus.xlsx`

El objetivo principal del proyecto es la producción de un documento **estilo artículo científico** sobre el análisis de los datos de `melocactus.xlsx` en el 2015 y 2019 y que incluya los siguientes elementos:

### "Abstract" (para prepararlo al final)

Debe incluir:

-   Párrafo sobre el planteamiento del problema o pregunta, hipótesis principal.
-   Párrafo sobre la metodología y análisis realizados.
-   Párrafo sobre los resultados principales y conclusión.

### Introducción

Debe incluir:

-   Información general sobre la especie *Melocactus intortus* y su presencia en Puerto Rico y el Caribe.
-   Riesgos de conservación de la especie por factores antropogénicos y perturbaciones naturales (huracán María).
-   Preguntas de investigación.
-   Hipótesis de trabajo, con premisa y predicción.
-   Una foto o gráfico relacionado al tema.

### Metodología Estadística

Para el análisis de los datos debe incluir al menos dos de las pruebas estadísticas vistas en el taller.

Debe incluir:

-   Descripción de las variables a analizar (metadata).
-   Análisis exploratorio de los datos que va a realizar.
-   Justificación de las pruebas estadísticas a utilizar.
-   Hipótesis nula y alternativa para cada prueba estadística.

### Resultados

Debe incluir:

-   Tablas (puede hacerlas en Word) y gráficos (con sus respectivas leyendas descriptivas) de los resultados de las estadísticas descriptivas y las pruebas estadísticas.
-   Párrafos explicativos de los resultados de pruebas estadísticas y su interpretación.

### Discusión y Conclusión

Debe incluir:

-   Contrastar los resultados de las pruebas estadísticas con las hipótesis planteadas.
-   Discusión de los resultados en el contexto de la literatura sobre las poblaciones de *Melocactus intortus* y su estado de conservación.
-   Limitaciones del estudio y posibles mejoras.
-   Conclusiones finales.

### Referencias

Las referencias pueden estar en cualquier formato, pero deben ser consistentes e incluir: autores, año, título, revista o editorial, volumen, páginas y DOI.
